#!/bin/bash -e
cd "$(dirname "$0")"


curl 'https://corona.ministryinfo.gov.lb/' > tmp.out

(
cat daily_data_*.csv | awk '/20/{print "existing," $0}'
cat tmp.out | grep -E 'cat_str =|cat_str.push|data: |name: '
) \
  | awk -F\'\|\" '

BEGIN{
  tr["العدد اليومي" "_1"] = "new_cases"
  tr["العدد اﻹجمالي" "_1"] = "total_cases"
  tr["العدد اليومي" "_2"] = "quarantined_cases"
  tr["حالات نقلها الصليب اﻷحمر" "_1"] = "transported_by_red_cross"
  # tr["حالات منقولة الى المستشفى" "_1"] = "transfered_to_hospital"
  # tr["اصابات"] = "cases_monthly"
  # tr["حالات حجر"] = "quarantines_monthly"
  num_columns = 0
  for (id in tr) {
    num_columns ++
    columns[num_columns] = tr[id]
  }
}

/^existing,/{
  split($0, tokens, ",")
  date_std = tokens[2]
  all_dates[date_std] = date_std
  all_values["total_cases@" date_std] = tokens[3]
  all_values["new_cases@" date_std] = tokens[4]
  all_values["quarantined_cases@" date_std] = tokens[5]
  all_values["transported_by_red_cross@" date_std] = tokens[6]
}

/var cat_str/{
  num_dates = 0
  for (i in dates) {
    delete dates[i]
  }
}

/cat_str.push/{
  num_dates ++
  dates[num_dates] = $2
}

/name:/{
  num_names[$2] = 1 + num_names[$2]
  name = tr[$2 "_" num_names[$2]]
}

/data:/{
  if (name) {
    split($0, tokens, "\\[|\\]")
    split(tokens[2], values, ",")
    for (i = 1; i <= num_dates; ++i) {
      date = dates[i]
      cmd = "date -f \"%d %B %Y\" -j \"" date "\" \"+%Y-%m-%d\" || echo FAIL"
      cmd | getline date_std
      close(cmd)
      if (date_std != "FAIL") {
        all_dates[date_std] = date_std
        all_values[name "@" date_std] = values[i]
      }
    }
  }
}

END{
  printf "date"
  for (idx in columns) {
    printf "," columns[idx]
  }
  printf "\n"
  for (date_std in all_dates) {
    printf "%s", date_std
    for (id in columns) {
      name = columns[id]
      printf ",%s", all_values[name "@" date_std]
    }
    printf "\n"
  }
}
' 2>/dev/null \
  | sort -n > daily_data.csv

# quarantined per casa
DATA="$(cat tmp.out | grep -A1 "حالات حجر" | tail -1 | cut -d[ -f2 | cut -d] -f1 )"
if ! grep "$DATA" quarantined.csv; then
  echo "$(date +%Y-%m-%d),$DATA" >> quarantined.csv
fi

# Cases per district
function per_district() {
cat tmp.out | grep -A 10 -B 169 '#casesbydistricts' | awk '
BEGIN {
  num_district = 0
}
/cat_str.push/{
  split($0, tokens, "'\''")
  num_district ++
  district[tokens[2]] = num_district
}
/data:/{
  split($0, tokens0, "[")
  split(tokens0[2], tokens1, "]")
  split(tokens1[1], cases, ",")
}
END{
  printf "%s,", cases[district["بيروت"]]
  printf "%s,", cases[district["المتن"]]
  printf "%s,", cases[district["بعبدا"]]
  printf "%s,", cases[district["الشوف"]]
  printf "%s,", cases[district["كسروان"]]
  printf "%s,", cases[district["عكار"]]
  printf "%s,", cases[district["زحلة"]]
  printf "%s,", cases[district["بشري"]]
  printf "%s,", cases[district["جبيل"]]
  printf "%s,", cases[district["زغرتا"]]
  printf "%s,", cases[district["صور"]]
  printf "%s,", cases[district["عاليه"]]
  printf "%s,", cases[district["طرابلس"]]
  printf "%s,", cases[district["البترون"]]
  printf "%s,", cases[district["الضنية"]]
  printf "%s,", cases[district["صيدا"]]
  printf "%s,", cases[district["النبطية"]]
  printf "%s,", cases[district["بعلبك"]]
  printf "%s,", cases[district["الكورة"]]
  printf "%s,", cases[district["بنت جبيل"]]
  printf "%s,", cases[district["مرجعيون"]]
  printf "%s,", cases[district["البقاع الغربي"]]
  printf "%s,", cases[district["جزين"]]
  printf "%s,", cases[district["راشيا"]]
  printf "%s,", cases[district["الهرمل"]]
  printf "%s\n", cases[district["غير محدد"]]
}
'
}

DATA="$(per_district)"
if ! grep "$DATA" per_district.csv; then
  echo "$(date +%Y-%m-%d),$DATA" >> per_district.csv
fi
